apiVersion: v1
kind: Service
metadata:
  name: author-nodeport
spec:
  type: NodePort
  selector:
    app: author
  ports:
    - name: author-nodeport
      port: 80
      targetPort: 80
      nodePort: 30002