apiVersion: v1
kind: Service
metadata:
  name: book-nodeport
spec:
  type: NodePort
  selector:
    app: book
  ports:
    - name: book-http
      port: 80
      targetPort: 80
      nodePort: 30001

